apiVersion: v1
kind: Service
metadata:
  name: ngrok-service
spec:
  selector:
    app: ngrok
  type: NodePort
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30001 
