apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-deployment
  labels:
    app: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: ngrok/ngrok
          env:
            - name: NGROK_AUTHTOKEN
              valueFrom:
                secretKeyRef:
                  name: ngrok-authtoken-secret
                  key: authtoken
          args:
            - "http"
            - "rails-app-service:3000"
          ports:
            - containerPort: 4040 
